# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'selfSizingCells' do

pod 'Alamofire', '~> 3.1.3'
pod 'SwiftyJSON', '~> 2.3.1'

end

target 'selfSizingCellsTests' do

end

target 'selfSizingCellsUITests' do

end

